name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: QEMU 준비하기
        uses: docker/setup-qemu-action@v3

      - name: Buildx 준비하기
        uses: docker/setup-buildx-action@v3

      - name: Docker hub 로그인하기
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드하고 푸시하기
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            navystack/nginx-pagespeed:1.25.3
            navystack/nginx-pagespeed:latest
            navystack/nginx-pagespeed:mainline
            navystack/nginx-pagespeed:dev
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
